name: CI

on:
  pull_request:
    branches: [dev, main]
  push:
    branches: [dev]

permissions:
  contents: read

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        working-directory: backend
        run: dotnet restore

      - name: Build
        working-directory: backend
        run: dotnet build --configuration Release --no-restore

      # Run tests only if any *Tests.csproj exists anywhere
      - name: Test (if test projects exist)
        if: ${{ hashFiles('**/*Tests.csproj') != '' }}
        run: |
          # Find and run each test project
          for proj in $(git ls-files '**/*Tests.csproj'); do
            echo "Running tests in $proj"
            dotnet test "$proj" --no-build --verbosity normal
          done
        shell: bash

  build-frontend:
    if: ${{ hashFiles('frontend/package.json') != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps (works with or without lockfile)
        working-directory: frontend
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Build (Vite)
        working-directory: frontend
        run: npm run build
