name: CI

on:
  pull_request:
    branches: [dev, main]
  push:
    branches: [dev]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        working-directory: backend
        run: dotnet restore

      - name: Build
        working-directory: backend
        run: dotnet build --configuration Release --no-restore

      # Only run tests if any exist
      - name: Test (if test projects exist)
        run: |
          if ls **/*Tests.csproj 1> /dev/null 2>&1; then
            for proj in $(ls **/*Tests.csproj); do
              echo "Running tests in $proj"
              dotnet test "$proj" --no-build --verbosity normal
            done
          else
            echo "No test projects found, skipping"
          fi
        shell: bash

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Check for frontend
        id: check_frontend
        run: |
          if [ ! -f frontend/package.json ]; then
            echo "no-frontend=true" >> $GITHUB_OUTPUT
          fi

      - name: Install deps
        if: steps.check_frontend.outputs.no-frontend != 'true'
        working-directory: frontend
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Build (skip if no frontend)
        if: steps.check_frontend.outputs.no-frontend != 'true'
        working-directory: frontend
        run: npm run build || echo "No build script, skipping"
